### ISSUE TITLE
Does not launch

### ISSUE THREAD

**Issue by vtf6259** [CottonMC/json-factory#16]
Does not launch
The log info is
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346)
        at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
        at io.github.cottonmc.jsonfactory.gui.Gui$Companion.show(Gui.kt:228)
        at io.github.cottonmc.jsonfactory.gui.MainKt.main(Main.kt:5)
        at io.github.cottonmc.jsonfactory.gui.MainKt.main(Main.kt)
Caused by: java.lang.NullPointerException: Cannot invoke "org.pushingpixels.substance.api.SubstanceSkin.getBackgroundColorScheme(org.pushingpixels.substance.api.DecorationAreaType)" because the return value of "org.pushingpixels.substance.api.SubstanceLookAndFeel.getCurrentSkin(java.awt.Component)" is null
        at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getDefaultBackgroundColor(SubstanceColorUtilities.java:759)
        at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getBackgroundFillColor(SubstanceColorUtilities.java:661)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.__org__pushingpixels__substance__internal__ui__SubstancePanelUI__installDefaults(SubstancePanelUI.java:74)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.installDefaults(SubstancePanelUI.java)
        at org.pushingpixels.substance.swingx.SubstancePanelUI.__org__pushingpixels__substance__swingx__SubstancePanelUI__installDefaults(SubstancePanelUI.java)
        at org.pushingpixels.substance.swingx.SubstancePanelUI.installDefaults(SubstancePanelUI.java)
        at java.desktop/javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:67)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.__org__pushingpixels__substance__internal__ui__SubstancePanelUI__installUI(SubstancePanelUI.java)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.installUI(SubstancePanelUI.java)
        at org.pushingpixels.substance.swingx.SubstancePanelUI.__org__pushingpixels__substance__swingx__SubstancePanelUI__installUI(SubstancePanelUI.java)
        at org.pushingpixels.substance.swingx.SubstancePanelUI.installUI(SubstancePanelUI.java)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:740)
        at java.desktop/javax.swing.JPanel.setUI(JPanel.java:153)
        at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:129)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:89)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:112)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:120)
        at java.desktop/javax.swing.JRootPane.createGlassPane(JRootPane.java:509)
        at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:336)
        at java.desktop/javax.swing.JFrame.createRootPane(JFrame.java:279)
        at java.desktop/javax.swing.JFrame.frameInit(JFrame.java:258)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:181)
        at io.github.cottonmc.jsonfactory.gui.Gui.<init>(Gui.kt:17)
        at io.github.cottonmc.jsonfactory.gui.Gui.<init>(Gui.kt:16)
        at io.github.cottonmc.jsonfactory.gui.Gui$Companion$show$1.run(Gui.kt:229)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Juuxel** [comment]
This project is not maintained.
